#ifndef CHROOT_SETUP_SCRIPT_H
#define CHROOT_SETUP_SCRIPT_H

static const char chroot_setup_script_content[] =
    "#!/bin/bash\n"
    "\n"
    "arch=$1\n"
    "chroot_path=$2\n"
    "logfile=$3\n"
    "qemu_static_bin=\"/usr/bin/qemu-${arch}-static\"\n"
    "\n"
    "# Controlla che i parametri siano stati passati\n"
    "if [ -z \"$arch\" ] || [ -z \"$chroot_path\" ] || [ -z \"$logfile\" ]; then\n"
    "    echo \"From chrootSetup.sh: Usage: $0 <architecture> <chroot_path> <logfile>\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Controllo che qemu static binary esista\n"
    "if [ ! -f \"$qemu_static_bin\" ]; then\n"
    "    echo \"From chrootSetup.sh: Error: QEMU static binary $qemu_static_bin not found on host.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Reindirizza output al logfile (nota: questo è ancora il log file sull'host, non dentro il chroot)\n"
    "exec >> \"$logfile\" 2>&1\n"
    "echo \"From chrootSetup.sh: Starting chroot setup for $arch at $chroot_path\"\n"
    "\n"
    "# Controlla se il chroot esiste già (semplice controllo sulla directory)\n"
    "if [ -d \"$chroot_path/debootstrap\" ]; then\n"
    "    echo \"From chrootSetup.sh: Chroot directory $chroot_path already seems to be set up (debootstrap dir exists). Skipping debootstrap.\"\n"
    "    exit 0\n"
    "fi\n"
    "\n"
    "echo \"From chrootSetup.sh: Running debootstrap first stage for $arch...\"\n"
    "# Se siamo su riscv64 devo usare trixie come distro, non bookworm\n"
    "distro=\"bookworm\"\n"
    "if [ \"$arch\" = \"riscv64\" ]; then\n"
    "    echo \"From chrootSetup.sh: Using trixie as the distribution for architecture $arch.\"\n"
    "    distro=\"trixie\"\n"
    "else\n"
    "    echo \"From chrootSetup.sh: Using bookworm as the distribution for architecture $arch.\"\n"
    "fi\n"
    "\n"
    "sudo debootstrap --arch=\"$arch\" --foreign \"$distro\" \"$chroot_path\" http://deb.debian.org/debian\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"From chrootSetup.sh: Error: debootstrap first stage failed for $arch.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "echo \"From chrootSetup.sh: Copying $qemu_static_bin to $chroot_path/usr/bin/...\"\n"
    "sudo cp \"$qemu_static_bin\" \"$chroot_path/usr/bin/\"\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"From chrootSetup.sh: Error: Failed to copy qemu static binary.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "echo \"From chrootSetup.sh: Running debootstrap second stage for $arch...\"\n"
    "sudo chroot \"$chroot_path\" /debootstrap/debootstrap --second-stage\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"From chrootSetup.sh: Error: debootstrap second stage failed for $arch.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "echo \"From chrootSetup.sh: Chroot setup completed successfully for $arch at $chroot_path.\"\n"
    "exit 0\n";

#endif
