#ifndef COPY_SOURCE_SCRIPT_H
#define COPY_SOURCE_SCRIPT_H

static const char copy_source_script_content[] =
    "#!/bin/bash\n"
    "\n"
    "host_sshlirp_src=$1\n"
    "host_libslirp_src=$2\n"
    "chroot_path=$3\n"
    "chroot_sshlirp_dir=$4\n"
    "chroot_libslirp_dir=$5\n"
    "logfile=$6\n"
    "\n"
    "# Controlla che i parametri siano stati passati\n"
    "if [ -z \"$host_sshlirp_src\" ] || [ -z \"$host_libslirp_src\" ] || [ -z \"$chroot_path\" ] || [ -z \"$chroot_sshlirp_dir\" ] || [ -z \"$chroot_libslirp_dir\" ] || [ -z \"$logfile\" ]; then\n"
    "    echo \"From copySource.sh: Usage: $0 <host_sshlirp_src> <host_libslirp_src> <chroot_path> <chroot_sshlirp_dir> <chroot_libslirp_dir> <logfile>\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Reindirizza output al logfile (anche qui si tratta di un log file sull'host, non dentro il chroot - sebbene sempre un log file non condiviso ma personale del thread)\n"
    "exec >> \"$logfile\" 2>&1\n"
    "echo \"From copySource.sh: Copying sources into chroot $chroot_path\"\n"
    "\n"
    "chroot_sshlirp_full_path=\"$chroot_path$chroot_sshlirp_dir\"\n"
    "chroot_libslirp_full_path=\"$chroot_path$chroot_libslirp_dir\"\n"
    "\n"
    "# Crea le directory di destinazione dentro il chroot se non esistono (in teoria dovrebbero essere già esistenti grazie alla funzione check_worker_dirs invocata dal worker)\n"
    "echo \"From copySource.sh: Ensuring copy point $chroot_sshlirp_full_path exists.\"\n"
    "sudo mkdir -p \"$chroot_sshlirp_full_path\"\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"From copySource.sh: Error creating copy point $chroot_sshlirp_full_path.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "echo \"From copySource.sh: Ensuring copy point $chroot_libslirp_full_path exists.\"\n"
    "sudo mkdir -p \"$chroot_libslirp_full_path\"\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"From copySource.sh: Error creating copy point $chroot_libslirp_full_path.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Copio sshlirp source\n"
    "# Prima controllo se è già copiato per evitare errori\n"
    "if [ -d \"$chroot_sshlirp_full_path/.git\" ]; then\n"
    "    echo \"From copySource.sh: $host_sshlirp_src already copied to $chroot_sshlirp_full_path.\"\n"
    "else\n"
    "    echo \"From copySource.sh: Copying $host_sshlirp_src to $chroot_sshlirp_full_path\"\n"
    "    sudo cp -r \"$host_sshlirp_src\"/* \"$chroot_sshlirp_full_path/\"\n"
    "    if [ $? -ne 0 ]; then\n"
    "        echo \"From copySource.sh: Error copying $host_sshlirp_src to $chroot_sshlirp_full_path.\"\n"
    "        exit 1\n"
    "    fi\n"
    "fi\n"
    "\n"
    "# Copio libslirp source\n"
    "if [ -d \"$chroot_libslirp_full_path/.git\" ]; then\n"
    "    echo \"From copySource.sh: $host_libslirp_src already copied to $chroot_libslirp_full_path.\"\n"
    "else\n"
    "    echo \"From copySource.sh: Copying $host_libslirp_src to $chroot_libslirp_full_path\"\n"
    "    sudo cp -r \"$host_libslirp_src\"/* \"$chroot_libslirp_full_path/\"\n"
    "    if [ $? -ne 0 ]; then\n"
    "        echo \"From copySource.sh: Error copying $host_libslirp_src to $chroot_libslirp_full_path.\"\n"
    "        exit 1\n"
    "    fi\n"
    "fi\n"
    "\n"
    "echo \"From copySource.sh: Source copying completed successfully.\"\n"
    "exit 0\n";

#endif
