#ifndef GIT_CLONE_SCRIPT_H
#define GIT_CLONE_SCRIPT_H

static const char git_clone_script_content[] =
    "#!/bin/bash\n"
    "\n"
    "what2clone=$1\n"
    "where2clone=$2\n"
    "logfile=$3\n"
    "versioning_file=$4\n"
    "\n"
    "sshlirp_git_clone=1\n"
    "\n"
    "# Check if parameters were passed\n"
    "if [ -z \"$what2clone\" ] || [ -z \"$where2clone\" ] || [ -z \"$logfile\" ]; then\n"
    "    echo \"From gitClone.sh: Usage: $0 <repository_url> <destination_directory> <logfile>\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Check if the versioning file was passed. If not, I'm cloning libslirp, otherwise I'm cloning sshlirp and will need to modify the versioning file\n"
    "if [ -z \"$versioning_file\" ]; then\n"
    "    sshlirp_git_clone=0\n"
    "fi\n"
    "\n"
    "# Check that the log file exists\n"
    "if [ ! -f $logfile ]; then\n"
    "    echo \"Error: From gitClone.sh: Logfile does not exist.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Redirect command outputs and echoes to the log file\n"
    "exec >> $logfile 2>&1\n"
    "\n"
    "# Check that the cloning path is valid\n"
    "if [ ! -d $where2clone ]; then\n"
    "    echo \"Error: From gitClone.sh: Invalid input. Please provide a valid directory.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "if [ $sshlirp_git_clone -eq 1 ]; then\n"
    "    # Check that the versioning file exists\n"
    "    if [ ! -f $versioning_file ]; then\n"
    "        echo \"Error: From gitClone.sh (for sshlirp cloning): Versioning file does not exist: $versioning_file\"\n"
    "        exit 1\n"
    "    fi\n"
    "fi\n"
    "\n"
    "# Check if there is already a Git repository in the directory\n"
    "if [ -d \"$where2clone/.git\" ]; then\n"
    "    echo \"From gitClone.sh: Info: $where2clone already contains a Git repository.\"\n"
    "    exit 0 # nothing to clone\n"
    "fi\n"
    "\n"
    "# Clone the repository\n"
    "echo \"From gitClone.sh: Cloning from $what2clone into $where2clone...\"\n"
    "git clone $what2clone $where2clone\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"Error: From gitClone.sh: Failed to clone repository.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "if [ $sshlirp_git_clone -eq 1 ]; then\n"
    "    # Check if there is a tag and if so, write it to the versioning file\n"
    "    cd $where2clone\n"
    "    if [ $? -ne 0 ]; then\n"
    "        echo \"Error: From gitClone.sh (for sshlirp cloning): Failed to change directory to $where2clone.\"\n"
    "        exit 1\n"
    "    fi\n"
    "    current_tag=$(git describe --tags --abbrev=0)\n"
    "\n"
    "    if [ -n \"$current_tag\" ]; then\n"
    "        echo \"From gitClone.sh (for sshlirp cloning): Found current tag: $current_tag\"\n"
    "        echo \"From gitClone.sh (for sshlirp cloning): Writing current tag to versioning file: $versioning_file\"\n"
    "        echo \"$current_tag\" >> $versioning_file\n"
    "    else\n"
    "        echo \"From gitClone.sh (for sshlirp cloning): No tags found.\"\n"
    "    fi\n"
    "fi\n"
    "\n"
    "echo \"From gitClone.sh: Cloning completed successfully.\"\n"
    "exit 2 # clone was performed\n";
#endif
