#ifndef MODIFY_VDENS_SCRIPT_H
#define MODIFY_VDENS_SCRIPT_H

static const char modify_vdens_script_content[] =
    "#!/bin/bash\n"
    "\n"
    "vdens_c_path=$1\n"
    "log_file=$2\n"
    "\n"
    "# Controllo se i parametri sono stati passati\n"
    "if [ -z \"$vdens_c_path\" ] || [ -z \"$log_file\" ]; then\n"
    "    echo \"Usage: $0 <path_to_vdens_c> <log_file>\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Controlla che il file di log esista\n"
    "if [ ! -f $log_file ]; then\n"
    "    echo \"Error: From gitClone.sh: Logfile does not exist.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Reindirizza gli output dei comandi e gli echo nel file di log\n"
    "exec >> $log_file 2>&1\n"
    "\n"
    "# Controlla che il file sorgente di vdens esista\n"
    "if [ ! -f \"$vdens_c_path\" ]; then\n"
    "    echo \"Error: From modifyVdens.sh: vdens.c file does not exist at $vdens_c_path\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Controllo se sono già state applicate le modifiche corrette a vdens.c (cerco se sono già presenti i commenti che andrei a fare)\n"
    "# nota: non posso fare controlli su .git in quanto sembra che dopo il pull non vi sia alcuna dir .git\n"
    "if grep -q '/\\*uid_gid_map(' \"$vdens_c_path\" && grep -q '/\\*CLONE_NEWUSER' \"$vdens_c_path\"; then\n"
    "    echo \"From modifyVdens.sh: The modifications to $vdens_c_path have already been applied.\"\n"
    "    exit 0\n"
    "fi\n"
    "\n"
    "# Modifica il file vdens.c per commentare le chiamate a uid_gid_map e il flag CLONE_NEWUSER.\n"
    "sed -i 's,\\(uid_gid_map(.*);\\),/*&*/,' \"$vdens_c_path\"\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"Error: From modifyVdens.sh: Failed to comment out uid_gid_map calls in $vdens_c_path\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "sed -i 's,CLONE_NEWUSER[[:space:]]*|,/*&*/,g' \"$vdens_c_path\"\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"Error: From modifyVdens.sh: Failed to comment out CLONE_NEWUSER in $vdens_c_path\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "echo \"From modifyVdens.sh: Successfully modified $vdens_c_path to comment out uid_gid_map calls and CLONE_NEWUSER flag.\"\n"
    "exit 0\n";
#endif  // MODIFY_VDENS_SCRIPT_H