#ifndef REMOVE_SOURCE_COPY_SCRIPT_H
#define REMOVE_SOURCE_COPY_SCRIPT_H

static const char remove_source_copy_script_content[] =
    "#!/bin/bash\n"
    "\n"
    "chroot_path=$1\n"
    "chroot_sshlirp_dir=$2\n"
    "chroot_libslirp_dir=$3\n"
    "logfile=$4\n"
    "\n"
    "# Check if parameters were passed\n"
    "if [ -z \"$chroot_path\" ] || [ -z \"$chroot_sshlirp_dir\" ] || [ -z \"$chroot_libslirp_dir\" ] || [ -z \"$logfile\" ]; then\n"
    "    echo \"From removeSourceCopy.sh: Usage: $0 <chroot_path> <chroot_sshlirp_dir> <chroot_libslirp_dir> <logfile>\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Redirect output to the logfile (which in this case will always be the thread's personal log file but on the host)\n"
    "exec >> \"$logfile\" 2>&1\n"
    "echo \"From removeSourceCopy.sh: Removing sources copy from chroot $chroot_path\"\n"
    "\n"
    "chroot_sshlirp_full_path=\"$chroot_path$chroot_sshlirp_dir\"\n"
    "chroot_libslirp_full_path=\"$chroot_path$chroot_libslirp_dir\"\n"
    "\n"
    "# Remove sshlirp source without deleting the chroot_sshlirp_dir directory\n"
    "if [ -d \"$chroot_sshlirp_full_path/.git\" ]; then\n"
    "    echo \"From removeSourceCopy.sh: Removing $chroot_sshlirp_full_path contents.\"\n"
    "    sudo rm -rf \"$chroot_sshlirp_full_path/\"*\n"
    "    if [ $? -ne 0 ]; then\n"
    "        echo \"Error: From removeSourceCopy.sh: Error removing contents of $chroot_sshlirp_full_path.\"\n"
    "        exit 1\n"
    "    fi\n"
    "else\n"
    "    echo \"From removeSourceCopy.sh: $chroot_sshlirp_full_path does not exist or is not a valid directory.\"\n"
    "fi\n"
    "\n"
    "# Remove libslirp source without deleting the chroot_libslirp_dir directory\n"
    "if [ -d \"$chroot_libslirp_full_path/.git\" ]; then\n"
    "    echo \"From removeSourceCopy.sh: Removing $chroot_libslirp_full_path contents.\"\n"
    "    sudo rm -rf \"$chroot_libslirp_full_path/\"*\n"
    "    if [ $? -ne 0 ]; then\n"
    "        echo \"Error: From removeSourceCopy.sh: Error removing contents of $chroot_libslirp_full_path.\"\n"
    "        exit 1\n"
    "    fi\n"
    "else\n"
    "    echo \"From removeSourceCopy.sh: $chroot_libslirp_full_path does not exist or is not a valid directory.\"\n"
    "fi\n"
    "\n"
    "echo \"From removeSourceCopy.sh: Sources copy removed successfully from chroot $chroot_path.\"\n"
    "exit 0\n";

#endif
