#ifndef TEST_SCRIPT_H
#define TEST_SCRIPT_H

static const char test_script_content[] =
    "#!/bin/bash\n"
    "\n"
    "sshlirp_bin_path=$1     # note: sshlirp_bin_path is a relative path to the chroot\n"
    "chroot_path=$2\n"
    "thread_chroot_vdens_dir=$3\n"
    "host_log_file=$4\n"
    "chroot_log_file=$5\n"
    "\n"
    "absolute_chroot_vdens_dir=\"${chroot_path}/${thread_chroot_vdens_dir}\"\n"
    "\n"
    "# Check if parameters were passed\n"
    "if [ -z \"$sshlirp_bin_path\" ] || [ -z \"$chroot_path\" ] || [ -z \"$thread_chroot_vdens_dir\" ] || [ -z \"$host_log_file\" ] || [ -z \"$chroot_log_file\" ]; then\n"
    "    echo \"Usage: $0 <sshlirp_bin_path> <chroot_path> <thread_chroot_vdens_dir> <host_log_file> <chroot_log_file>\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Check that the host log file exists\n"
    "if [ ! -f $host_log_file ]; then\n"
    "    echo \"Error: From test.sh: Host logfile does not exist.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Redirect command outputs and echoes to the log file\n"
    "exec >> $host_log_file 2>&1\n"
    "\n"
    "# Check that the chroot path exists\n"
    "if [ ! -d \"$chroot_path\" ]; then\n"
    "    echo \"Error: From test.sh: Chroot path does not exist at ${chroot_path}\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Configure the TUN device necessary for vdens to work\n"
    "echo \"Configuring TUN device for vdens...\"\n"
    "if [ ! -c /dev/net/tun ]; then\n"
    "    echo \"Error: From test.sh: /dev/net/tun does not exist on the host.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Get major and minor numbers for /dev/net/tun\n"
    "read MAJOR MINOR < <(ls -l /dev/net/tun | awk '{gsub(\",\",\"\"); print $5, $6}')\n"
    "if [ -z \"$MAJOR\" ] || [ -z \"$MINOR\" ]; then\n"
    "    echo \"Error: From test.sh: Unable to obtain major/minor numbers for /dev/net/tun.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Create the /dev/net directory in the chroot (if it doesn't already exist)\n"
    "sudo mkdir -p \"${chroot_path}/dev/net\"\n"
    "if [ ! -d \"${chroot_path}/dev/net\" ]; then\n"
    "    echo \"Error: From test.sh: Unable to create directory /dev/net in chroot.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Create the TUN device in the chroot with the obtained major and minor numbers if it doesn't already exist\n"
    "if [ ! -c \"${chroot_path}/dev/net/tun\" ]; then\n"
    "    echo \"Creating TUN device in chroot...\"\n"
    "    sudo mknod \"${chroot_path}/dev/net/tun\" c $MAJOR $MINOR\n"
    "    if [ $? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh: Unable to create TUN device in chroot.\"\n"
    "        exit 1\n"
    "    fi\n"
    "    echo \"TUN device created successfully in chroot.\"\n"
    "else\n"
    "    echo \"TUN device already exists in chroot.\"\n"
    "fi\n"
    "\n"
    "# Set permissions for the TUN device in the chroot\n"
    "# Note: 666 permissions are necessary to allow vdens to access it\n"
    "sudo chmod 666 \"${chroot_path}/dev/net/tun\"\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"Error: From test.sh: Unable to set permissions for TUN device in chroot.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Create the configuration file for vdens (due to a mount bug, it is necessary to generate the resolv.conf file beforehand)\n"
    "echo \"Creating resolv.conf in chroot...\"\n"
    "echo \"nameserver 9.9.9.9\" | sudo tee \"${chroot_path}/etc/resolv.conf\" > /dev/null\n"
    "\n"
    "# Enter the chroot\n"
    "echo \"Starting test script inside chroot...\"\n"
    "\n"
    "# Redirect command outputs and echoes to the chroot log file\n"
    "absolute_chroot_log_file_path=\"${chroot_path}${chroot_log_file}\"\n"
    "if [ ! -f \"$absolute_chroot_log_file_path\" ]; then\n"
    "    echo \"Warning: From test.sh: Chroot logfile does not exist at ${absolute_chroot_log_file_path}; test inside chroot logs will be saved in the host log file.\"\n"
    "else\n"
    "    exec >> \"$absolute_chroot_log_file_path\" 2>&1\n"
    "fi\n"
    "\n"
    "sudo chroot \"$chroot_path\" /bin/bash <<EOF\n"
    "\n"
    "    echo \"------- From test.sh (inside chroot): testing sshlirp binary at ${sshlirp_bin_path} inside ${chroot_path} -------\"\n"
    "\n"
    "    # Check for the existence of sshlirp_bin_path (it's a relative path to the chroot)\n"
    "    if [ ! -f \"$sshlirp_bin_path\" ]; then\n"
    "        echo \"Error: From test.sh: sshlirp binary does not exist at ${sshlirp_bin_path}\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    echo \"From test.sh (inside chroot): Installing dependencies...\"\n"
    "    apt-get update\n"
    "    apt-get install -y libcap-dev libexecs-dev\n"
    "    if [ \\$? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): Failed to install dependencies.\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    # Check for the existence of the vdens repo inside the chroot\n"
    "    if [ ! -d \"$thread_chroot_vdens_dir\" ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): vdens directory does not exist at $thread_chroot_vdens_dir\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    echo \"From test.sh (inside chroot): Compiling vdens...\"\n"
    "    cd \"$thread_chroot_vdens_dir\"\n"
    "    mkdir -p build\n"
    "    cd build\n"
    "    cmake ..\n"
    "    make\n"
    "    if [ \\$? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): Compilation of vdens failed.\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    # Start vdens, which executes sshlirp, which in turn executes a shell.\n"
    "    # The following commands are executed in that shell, in the correct namespace.\n"
    "    echo \"From test.sh (inside chroot): Entering vdens namespace to run tests...\"\n"
    "    ./vdens cmd://$sshlirp_bin_path /bin/bash <<'INNER_EOF'\n"
    "        set -e\n"
    "\n"
    "        # Now we are in the network namespace created by vdens\n"
    "        echo \"From test.sh (in vdens namespace): Configuring network... (actual configuration:)\"\n"
    "        ip a\n"
    "\n"
    "        echo \"From test.sh (in vdens namespace): Setting IP address and bringing up vde0...\"\n"
    "        ip addr add 10.0.2.15/24 dev vde0\n"
    "        if [ \\$? -ne 0 ]; then\n"
    "            echo \"Error: From test.sh (in vdens namespace): Unable to set IP address on vde0.\"\n"
    "            exit 1\n"
    "        fi\n"
    "\n"
    "        ip link set vde0 up\n"
    "        if [ \\$? -ne 0 ]; then\n"
    "            echo \"Error: From test.sh (in vdens namespace): Unable to bring up vde0.\"\n"
    "            exit 1\n"
    "        fi\n"
    "        echo \"From test.sh (in vdens namespace): Network configured successfully:\"\n"
    "        ip a\n"
    "\n"
    "        echo \"From test.sh (in vdens namespace): Pinging gateway through sshlirp...\"\n"
    "        ping -c 4 10.0.2.2\n"
    "        if [ \\$? -ne 0 ]; then\n"
    "            echo \"Error: From test.sh (in vdens namespace): Ping to gateway failed.\"\n"
    "            exit 1\n"
    "        fi\n"
    "        echo \"From test.sh (in vdens namespace): Ping successful.\"\n"
    "\n"
    "        exit 0\n"
    "INNER_EOF\n"
    "\n"
    "    if [ \\$? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): Script inside vdens namespace failed.\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    echo \"------- From test.sh (inside chroot): successful testing inside ${chroot_path} -------\"\n"
    "\n"
    "    exit 0\n"
    "EOF\n"
    "\n"
    "# Restore host log file\n"
    "exec >> $host_log_file 2>&1\n"
    "\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"Error: From test.sh: Script inside chroot failed.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "echo \"...From test.sh (inside chroot): test script executed successfully.\"\n"
    "exit 0\n";

#endif  // TEST_SCRIPT_H