#ifndef TEST_SCRIPT_H
#define TEST_SCRIPT_H

static const char test_script_content[] =
    "#!/bin/bash\n"
    "\n"
    "sshlirp_bin_path=$1     # nota: sshlirp_bin_path è un percorso relativo al chroot\n"
    "chroot_path=$2\n"
    "thread_chroot_vdens_dir=$3\n"
    "host_log_file=$4\n"
    "chroot_log_file=$5\n"
    "\n"
    "absolute_chroot_vdens_dir=\"${chroot_path}/${thread_chroot_vdens_dir}\"\n"
    "\n"
    "# Controllo se i parametri sono stati passati\n"
    "if [ -z \"$sshlirp_bin_path\" ] || [ -z \"$chroot_path\" ] || [ -z \"$thread_chroot_vdens_dir\" ] || [ -z \"$host_log_file\" ] || [ -z \"$chroot_log_file\" ]; then\n"
    "    echo \"Usage: $0 <sshlirp_bin_path> <chroot_path> <thread_chroot_vdens_dir> <host_log_file> <chroot_log_file>\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Controllo che il file di log sull'host esista\n"
    "if [ ! -f $host_log_file ]; then\n"
    "    echo \"Error: From test.sh: Host logfile does not exist.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Reindirizzo gli output dei comandi e gli echo nel file di log\n"
    "exec >> $host_log_file 2>&1\n"
    "\n"
    "# Controlla che il path di chroot esista\n"
    "if [ ! -d \"$chroot_path\" ]; then\n"
    "    echo \"Error: From test.sh: Chroot path does not exist at ${chroot_path}\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Configuro il device TUN necessario per il funzionamento di vdens\n"
    "echo \"Configuring TUN device for vdens...\"\n"
    "if [ ! -c /dev/net/tun ]; then\n"
    "    echo \"Error: From test.sh: /dev/net/tun does not exist on the host.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Ottengo i numeri major e minor per /dev/net/tun\n"
    "read MAJOR MINOR < <(ls -l /dev/net/tun | awk '{gsub(\",\",\"\"); print $5, $6}')\n"
    "if [ -z \"$MAJOR\" ] || [ -z \"$MINOR\" ]; then\n"
    "    echo \"Error: From test.sh: Unable to obtain major/minor numbers for /dev/net/tun.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Creo la directory /dev/net nel chroot (se ancora non esiste)\n"
    "sudo mkdir -p \"${chroot_path}/dev/net\"\n"
    "if [ ! -d \"${chroot_path}/dev/net\" ]; then\n"
    "    echo \"Error: From test.sh: Unable to create directory /dev/net in chroot.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Crea il device TUN nel chroot con i numeri major e minor ottenuti se non esistono già\n"
    "if [ ! -c \"${chroot_path}/dev/net/tun\" ]; then\n"
    "    echo \"Creating TUN device in chroot...\"\n"
    "    sudo mknod \"${chroot_path}/dev/net/tun\" c $MAJOR $MINOR\n"
    "    if [ $? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh: Unable to create TUN device in chroot.\"\n"
    "        exit 1\n"
    "    fi\n"
    "    echo \"TUN device created successfully in chroot.\"\n"
    "else\n"
    "    echo \"TUN device already exists in chroot.\"\n"
    "fi\n"
    "\n"
    "# Imposta i permessi per il device TUN nel chroot\n"
    "# Nota: i permessi 666 sono necessari per permettere a vdens di accedere\n"
    "sudo chmod 666 \"${chroot_path}/dev/net/tun\"\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"Error: From test.sh: Unable to set permissions for TUN device in chroot.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Creazione del file di configurazione per vdens (a causa del bug di mount è necessario generare a priori il file di resolv.conf)\n"
    "echo \"Creating resolv.conf in chroot...\"\n"
    "echo \"nameserver 9.9.9.9\" | sudo tee \"${chroot_path}/etc/resolv.conf\" > /dev/null\n"
    "\n"
    "# Entro nel chroot\n"
    "echo \"Starting test script inside chroot...\"\n"
    "\n"
    "# Rendendizzo gli output dei comandi e gli echo nel file di log del chroot\n"
    "absolute_chroot_log_file_path=\"${chroot_path}${chroot_log_file}\"\n"
    "if [ ! -f \"$absolute_chroot_log_file_path\" ]; then\n"
    "    echo \"Warning: From test.sh: Chroot logfile does not exist at ${absolute_chroot_log_file_path}; test inside chroot logs will be saved in the host log file.\"\n"
    "else\n"
    "    exec >> \"$absolute_chroot_log_file_path\" 2>&1\n"
    "fi\n"
    "\n"
    "sudo chroot \"$chroot_path\" /bin/bash <<EOF\n"
    "\n"
    "    echo \"------- From test.sh (inside chroot): testing sshlirp binary at ${sshlirp_bin_path} inside ${chroot_path} -------\"\n"
    "\n"
    "    # Controlla l'esistenza del sshlirp_bin_path di sshlirp (è un percorso relativo al chroot)\n"
    "    if [ ! -f \"$sshlirp_bin_path\" ]; then\n"
    "        echo \"Error: From test.sh: sshlirp binary does not exist at ${sshlirp_bin_path}\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    echo \"From test.sh (inside chroot): Installing dependencies...\"\n"
    "    apt-get update\n"
    "    apt-get install -y libcap-dev libexecs-dev\n"
    "    if [ \\$? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): Failed to install dependencies.\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    # Controlla l'esistenza della repo vdens all'interno del chroot\n"
    "    if [ ! -d \"$thread_chroot_vdens_dir\" ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): vdens directory does not exist at $thread_chroot_vdens_dir\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    echo \"From test.sh (inside chroot): Compiling vdens...\"\n"
    "    cd \"$thread_chroot_vdens_dir\"\n"
    "    mkdir -p build\n"
    "    cd build\n"
    "    cmake ..\n"
    "    make\n"
    "    if [ \\$? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): Compilation of vdens failed.\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    # Avvia vdens, che esegue sshlirp, che a sua volta esegue una shell.\n"
    "    # I comandi seguenti vengono eseguiti in quella shell, nel namespace corretto.\n"
    "    echo \"From test.sh (inside chroot): Entering vdens namespace to run tests...\"\n"
    "    ./vdens cmd://$sshlirp_bin_path /bin/bash <<'INNER_EOF'\n"
    "        set -e\n"
    "\n"
    "        # Ora siamo nel namespace di rete creato da vdens\n"
    "        echo \"From test.sh (in vdens namespace): Configuring network... (actual configuration:)\"\n"
    "        ip a\n"
    "\n"
    "        echo \"From test.sh (in vdens namespace): Setting IP address and bringing up vde0...\"\n"
    "        ip addr add 10.0.2.15/24 dev vde0\n"
    "        if [ \\$? -ne 0 ]; then\n"
    "            echo \"Error: From test.sh (in vdens namespace): Unable to set IP address on vde0.\"\n"
    "            exit 1\n"
    "        fi\n"
    "\n"
    "        ip link set vde0 up\n"
    "        if [ \\$? -ne 0 ]; then\n"
    "            echo \"Error: From test.sh (in vdens namespace): Unable to bring up vde0.\"\n"
    "            exit 1\n"
    "        fi\n"
    "        echo \"From test.sh (in vdens namespace): Network configured successfully:\"\n"
    "        ip a\n"
    "\n"
    "        echo \"From test.sh (in vdens namespace): Pinging gateway through sshlirp...\"\n"
    "        ping -c 4 10.0.2.2\n"
    "        if [ \\$? -ne 0 ]; then\n"
    "            echo \"Error: From test.sh (in vdens namespace): Ping to gateway failed.\"\n"
    "            exit 1\n"
    "        fi\n"
    "        echo \"From test.sh (in vdens namespace): Ping successful.\"\n"
    "\n"
    "        exit 0\n"
    "INNER_EOF\n"
    "\n"
    "    if [ \\$? -ne 0 ]; then\n"
    "        echo \"Error: From test.sh (inside chroot): Script inside vdens namespace failed.\"\n"
    "        exit 1\n"
    "    fi\n"
    "\n"
    "    echo \"------- From test.sh (inside chroot): successful testing inside ${chroot_path} -------\"\n"
    "\n"
    "    exit 0\n"
    "EOF\n"
    "\n"
    "# Ripristino del log file dell'host\n"
    "exec >> $host_log_file 2>&1\n"
    "\n"
    "if [ $? -ne 0 ]; then\n"
    "    echo \"Error: From test.sh: Script inside chroot failed.\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "echo \"...From test.sh (inside chroot): test script executed successfully.\"\n"
    "exit 0\n";

#endif  // TEST_SCRIPT_H